version: '3.7'
services:
  twitter-to-kafka-service:
    image: ${GROUP_ID}/twitter.to.kafka.service:${SERVICE_VERSION:-latest}
    build:
      context: ../twitter-to-kafka-service
      dockerfile: ../twitter-to-kafka-service/Dockerfile
    ports:
      - "5005:5005"
    volumes:
      - "./docker-logs:/workspace/twitter-to-kafka-service/logs"
      - "./check-config-server-started.sh:/usr/bin/check-config-server-started.sh"
    user: root
    entrypoint: ["check-config-server-started.sh"]
    depends_on:
      - config-server
      - kafka-broker-1
      - kafka-broker-2
      - kafka-broker-3
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xms128m -Xmx256m"
      - "LOGGING_LEVEL_COM_BERKANTERDOGAN_MICROSERVICES_LAB=info"
      - "LOGGING_LEVEL_ROOT=info"
      - "KAFKA_CONFIG_TOPIC_NAME=twitter-topic"
      - "KAFKA_CONFIG_BOOTSTRAP_SERVERS=kafka-broker-1:9092, kafka-broker-2:9092, kafka-broker-3:9092"
      - "KAFKA_CONFIG_SCHEMA_REGISTRY_URL=http://schema-registry:8081"
      - "MOCK_ENABLED=true"
      - "TWITTER4J_ENABLED=false"
      - "SPRING_CLOUD_CONFIG_USERNAME=${CONFIG_SERVER_USER_NAME}"
      - "SPRING_CLOUD_CONFIG_PASSWORD=${CONFIG_SERVER_USER_PASSWORD}"
      - "SPRING_CLOUD_CONFIG_URI=http://config-server:8888"
      - "ENCRYPT_KEY=${ENCRYPT_KEY}"
    networks:
      - ${GLOBAL_NETWORK:-services}

  kafka-to-elastic-service:
    image: ${GROUP_ID}/kafka.to.elastic.service:${SERVICE_VERSION:-latest}
    build:
      context: ../kafka-to-elastic-service
      dockerfile: ../kafka-to-elastic-service/Dockerfile
    ports:
      - "5006:5006"
    volumes:
      - "./docker-logs:/workspace/kafka-to-elastic-service/logs"
      - "./check-kafka-topics-created.sh:/usr/bin/check-kafka-topics-created.sh"
    user: root
    entrypoint: [ "check-kafka-topics-created.sh" ]
    depends_on:
      - config-server
      - twitter-to-kafka-service
      - kafka-broker-1
      - kafka-broker-2
      - kafka-broker-3
      - elastic-1
      - elastic-2
      - elastic-3
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006 -Xms128m -Xmx256m"
      - "LOGGING_LEVEL_COM_BERKANTERDOGAN_MICROSERVICES_LAB=info"
      - "LOGGING_LEVEL_ROOT=info"
      - "KAFKA_CONFIG_TOPIC_NAME=twitter-topic"
      - "KAFKA_CONFIG_BOOTSTRAP_SERVERS=kafka-broker-1:9092, kafka-broker-2:9092, kafka-broker-3:9092"
      - "KAFKA_CONFIG_SCHEMA_REGISTRY_URL=http://schema-registry:8081"
      - "SPRING_CLOUD_CONFIG_USERNAME=${CONFIG_SERVER_USER_NAME}"
      - "SPRING_CLOUD_CONFIG_PASSWORD=${CONFIG_SERVER_USER_PASSWORD}"
      - "SPRING_CLOUD_CONFIG_URI=http://config-server:8888"
      - "ELASTIC_INDEX_NAME=twitter-index"
      - "ELASTIC_CONNECTION_URL=http://elastic-1:9200"
      - "ENCRYPT_KEY=${ENCRYPT_KEY}"
    networks:
      - ${GLOBAL_NETWORK:-services}

  config-server:
    image: ${GROUP_ID}/config.server:${SERVICE_VERSION:-latest}
    build:
      context: ../config-server
      dockerfile: ../config-server/Dockerfile
    ports:
      - "5007:5007"
      - "8888:8888"
    volumes:
      - "./docker-logs:/workspace/config-server/logs"
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5007 -Xms128m -Xmx256m"
      - "LOGGING_LEVEL_ROOT=info"
      - "SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME=${CONFIG_SERVER_GIT_USERNAME}"
      - "SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD=${CONFIG_SERVER_GIT_PASSWORD}"
      - "SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL=${CONFIG_SERVER_GIT_DEFAULT_LABEL}"
      - "SPRING_SECURITY_USER_NAME=${CONFIG_SERVER_USER_NAME}"
      - "SPRING_SECURITY_USER_PASSWORD=${CONFIG_SERVER_USER_PASSWORD}"
      - "ENCRYPT_KEY=${ENCRYPT_KEY}"
    networks:
      - ${GLOBAL_NETWORK:-services}