FROM amazoncorretto:11.0.14
MAINTAINER berkanterdogan
COPY target/twitter-to-kafka-service-0.0.1-SNAPSHOT.jar twitter-to-kafka-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/twitter-to-kafka-service-0.0.1-SNAPSHOT.jar"]